### ISSUE TITLE
[question] What am I supposed to do?

### ISSUE THREAD

**Issue by raffel080108** [VHSgunzo/NordCheck#1]
I have no idea how this is supposed to work. I just have some random files in a directory now and no instructions or ideas on how to use them.. help please!

**Comment by VHSgunzo** [comment]
Get the IP addresses of the NordVPN from the vpn configuration or from somewhere else and add them to the src/nord_ip file (there is already a couple)
Then add the logins and passwords to the src/vpn file and run the script
